service: dynatrace-oneagent-sample

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  # DYNATRACE: 
  # pull in Dynatrace OneAgent plugin (install first with "npm install --save-dev @dynatrace/serverless-oneagent")
  - "@dynatrace/serverless-oneagent"

package:
  individually: true
  excludeDevDependencies: true


provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1

functions:
  hello:
    handler: index.hello
    events:
      - http:
          method: GET
          path: hello

custom: 
  # import options from a Javascript file
  serverless-oneagent:
    options: '${ssm:/dynatrace/lambda/DT_LAMBDA_OPTIONS~true}'
